group=pl.syntaxdevteam
version=1.0.0-WIP
description=Plugin uwierzytelniającym, który umożliwia jednoczesną obsługę: graczy premium/online — uwierzytelnionych przez oficjalny system Microsoft/Mojang,  graczy non-premium/offline — uwierzytelnianych przez AuthGatewayX przy pomocy /register i /login.
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
