[versions]
kotlin = "2.4.20-RC2"

paper-api = "26.2.build.+"
minecraft = "26.2"

paperweight-userdev = "2.0.0-beta.23"
shadow = "9.6.1"
run-task = "3.1.0"
hikari = "7.1.0"
sqlite = "3.53.2.1"
argon2 = "2.12"
velocity-api = "4.1.0-SNAPSHOT"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
argon2-jvm = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
